angular.module(primaryApplicationName).constant('consts', {
	ROOT_DOMAIN: process.env.TLD ? process.env.TLD : 'lavaboom.co',
	DEFAULT_KEY_LENGTH: 2048,
	ESTIMATED_KEY_GENERATION_TIME_SECONDS: 24,
	INBOX_REDIRECT_DELAY: 1000,
	BACKUP_KEYS_REDIRECT_DELAY: 1000,
	ENVELOPE_DEFAULT_MAJOR_VERSION: 1,
	ENVELOPE_DEFAULT_MINOR_VERSION: 0,
	AUTOSAVE_TIMEOUT: 1000,
	LOADER_SHOW_DELAY: 100,
	FAST_ACTIONS_TIMEOUT: 250,
	INBOX_THREADS_CACHE_TTL: 60 * 1000,
	INBOX_EMAILS_CACHE_TTL: 60 * 1000
});