angular.module(primaryApplicationName).constant('consts', {
	LOGIN_URL: '/',
	ROOT_DOMAIN: 'lavaboom.io',
	DEFAULT_KEY_LENGTH: 2048,
	ESTIMATED_KEY_GENERATION_TIME_SECONDS: 24,
	INBOX_REDIRECT_DELAY: 1000,
	BACKUP_KEYS_REDIRECT_DELAY: 1000,
	ENVELOPE_DEFAULT_MAJOR_VERSION: 1,
	ENVELOPE_DEFAULT_MINOR_VERSION: 0,
	AUTOSAVE_TIMEOUT: 1000,
	FAST_ACTIONS_TIMEOUT: 250
});